dist: xenial
language: python
cache: pip
_test: &_test
  install:
    - pip install tox tox-virtualenv-no-download
  script:
    - tox
  after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOXENV -f $TRAVIS_BUILD_DIR/coverage.xml
_autorest_install: &_autorest_install
  before_install:
  - git clone https://github.com/Azure/autorest.python.git --branch autorestv3 --single-branch
  - pushd autorest.python
  - npm install # Install test server pre-requisites
  - popd
jobs:
  include:
    - stage: MyPy
      python: 3.6
      install:
        - pip install -r dev_requirements.txt
      script:
        - mypy msrest
        - python -c 'import typing; typing.TYPE_CHECKING = True; import msrest'  # Testing there is no circular dependencies in Type checking mode
    - stage: Test
      python: 2.7
      env: TOXENV=py27
      <<: *_test
    - stage: Test
      python: 3.5
      env: TOXENV=py35
      <<: *_test
    - stage: Test
      python: 3.6
      env: TOXENV=py36
      <<: *_test
    - stage: Test
      python: 3.7
      env: TOXENV=py37
      <<: *_test
    - stage: Test
      python: 3.8
      env: TOXENV=py38
      <<: *_test
    - stage: Test
      python: 2.7
      env: TOXENV=py27-autorest
      <<: *_autorest_install
      <<: *_test
    - stage: Test
      python: 3.5
      env: TOXENV=py35-autorest
      <<: *_autorest_install
      <<: *_test
    - stage: Test
      python: 3.6
      env: TOXENV=py36-autorest
      <<: *_autorest_install
      <<: *_test
    - stage: Test
      python: 3.7
      env: TOXENV=py37-autorest
      <<: *_autorest_install
      <<: *_test
    - stage: Test
      python: 3.8
      env: TOXENV=py38-autorest
      <<: *_autorest_install
      <<: *_test

  allow_failures:
    - env: TOXENV=py27-autorest
    - env: TOXENV=py35-autorest
    - env: TOXENV=py36-autorest
    - env: TOXENV=py37-autorest
    - env: TOXENV=py38-autorest
deploy:
  provider: pypi
  user: Laurent.Mazuel
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: '3.6'
